name: LearnConnect
options:
  bundleIdPrefix: com.learnconnect
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "14.0"

targets:
  LearnConnect:
    type: application
    platform: iOS
    sources:
      - path: LearnConnect
    settings:
      base:
        INFOPLIST_FILE: LearnConnect/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.learnconnect.app
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ""  # Add your team ID here if you have one
    info:
      path: LearnConnect/Info.plist
      properties:
        CFBundleDisplayName: LearnConnect
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiredDeviceCapabilities: [armv7]
